version: "3.9"
services:
  nginx:
    build:
      context: docker
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/web
  apache:
    image: httpd:latest
    ports:
      - '8080:80'
    volumes:
      - ./public/:/usr/local/apache2/htdocs