version: '3.7'

services:
  ubuntu-apache:
    container_name: ubuntu-apache
    build: ./services/ubuntu-apache
    volumes:
    - $PWD/services/ubuntu-apache/public:/var/www/html
    - $PWD/services/ubuntu-apache/etc/apache2/apache2.conf:/etc/apache2/apache2.conf
    ports:
    - "127.0.0.1:80:80"